hwakyong-Yoo/group4-eaten

server/build.gradle, server/src/main/java/com/example/group4eaten/api/PostApiController.java, server/src/main/java/com/example/group4eaten/dto/PostDto.java, server/src/main/java/com/example/group4eaten/entity/Post.java, server/src/main/java/com/example/group4eaten/entity/User.java, server/src/main/java/com/example/group4eaten/repository/PostRepository.java, server/src/main/java/com/example/group4eaten/repository/UserRepository.java, server/src/main/java/com/example/group4eaten/service/PostService.java, server/src/main/resources/application.properties
아직 API 명세서의 request body를 반영하지 못한 상태입니다.
=> feat-전체 게시물 조회, 새 게시물 작성, 상세 게시물 조회 / chore-url 일부 수정

server/src/main/java/com/example/group4eaten/entity/Like.java, server/src/main/java/com/example/group4eaten/entity/LikePK.java, server/src/main/java/com/example/group4eaten/like/api/LikeApiController.java, server/src/main/java/com/example/group4eaten/like/dto/LikeDto.java, server/src/main/java/com/example/group4eaten/like/service/LikeService.java
fix:좋아요 추가 기능 api test 후 수정
- 좋아요 추가 기능 api test 후 수정
=> [BE]fix:좋아요 추가 기능 api test 후 수정

server/src/main/java/com/example/group4eaten/like/api/LikeApiController.java
fix:좋아요 삭제 기능 api test 후 수정
- 좋아요 삭제 기능 api test 후 수정
=> [BE]fix:좋아요 삭제 기능 api test 후 수정

server/src/main/java/com/example/group4eaten/entity/Post.java, server/src/main/java/com/example/group4eaten/entity/User.java, server/src/main/resources/application.properties
[BE]build:datasource.url과 username, password 업데이트
로컬에서 aws 서버 DB 접속 가능한지 확인
=> [BE]build:datasource.url과 username, password 업데이트

README.md
=> Yhee527 patch 1

server/src/main/java/com/example/group4eaten/entity/Post.java, server/src/main/java/com/example/group4eaten/post/api/PostApiController.java, server/src/main/java/com/example/group4eaten/post/service/PostService.java
[BE]refactor: Post entity 대신 PostApiController에서 dto의 postId 값 검증
Post entity가 아닌 PostApiController에서 service를 호출하기 전에 dto의 postId 값 검증하도록 수정
=> [BE]refactor: Post entity 대신 PostApiController에서 dto의 postId 값 검증 / fix:게시글 수정 에러 고침

server/src/main/java/com/example/group4eaten/user/api/UserController.java, server/src/main/java/com/example/group4eaten/user/service/UserService.java
fix:아이디 중복체크, 닉네임 중복체크 api 추가
- 아이디 중복체크, 닉네임 중복체크 api 추가
=> [BE]fix:아이디 중복체크, 닉네임 중복체크 api 추가

server/src/main/java/com/example/group4eaten/entity/Post.java, server/src/main/java/com/example/group4eaten/post/dto/PostDto.java, server/src/main/java/com/example/group4eaten/post/service/PostService.java
fix:edit_YN을 Boolean 타입으로 변경하고 기본값 false 설정. 게시물 수정되면 true로 변경되게 설정
원래는 edit_YN이 수정여부에 상관없이 null 값으로 나왔음
fix:edit_YN을 Boolean 타입으로 변경하고 기본값을 false로 설정
imagepath나 content 둘 중 적어도 하나가 변경되었을 때만 true로 변경되게 설정
=> [BE]fix:edit_YN을 Boolean 타입으로 변경하고 기본값 false 설정. 게시물 수정되면 true로 변경되게 설정

server/src/main/java/com/example/group4eaten/entity/Post.java, server/src/main/java/com/example/group4eaten/post/api/PostApiController.java, server/src/main/java/com/example/group4eaten/post/dto/PostDto.java, server/src/main/java/com/example/group4eaten/post/service/PostService.java
fix:게시물 생성 시 date를 request body로 받지 않고 자동으로 들어가게 수정
date 타입을 LocalDate에서 String으로 변경
PostDto에 getCurrentFormattedDate() 추가해서 PostApiController의 create에서 사용
=> [BE]fix:게시물 생성 시 date를 request body로 받지 않고 자동으로 들어가게 수정

server/src/main/java/com/example/group4eaten/like/repository/LikeRepository.java, server/src/main/java/com/example/group4eaten/like/service/LikeService.java, server/src/main/java/com/example/group4eaten/post/api/PostApiController.java, server/src/main/java/com/example/group4eaten/post/repository/PostRepository.java, server/src/main/java/com/example/group4eaten/post/service/PostService.java
feat: 좋아요 개수 확인, 인기게시물 확인 api 추가
- 좋아요 개수 확인, 인기게시물 확인 api 추가
=> [BE] feat: 좋아요 개수 확인, 인기게시물 확인 api 추가

server/src/main/java/com/example/group4eaten/post/api/PostApiController.java, server/src/main/java/com/example/group4eaten/post/repository/PostRepository.java, server/src/main/java/com/example/group4eaten/post/service/PostService.java
feat: 전체 게시물 조회 페이징 구현
한 페이지당 10개의 게시물을 표시하고 postId 기준으로 내림차순 정렬하여 구현
=> [BE]feat: 전체 게시물 조회 페이징 구현

server/src/main/java/com/example/group4eaten/like/service/LikeService.java
fix: 좋아요 추가에서 좋아요가 이미 눌려져 있는 상태는 고려 안하도록 수정
- 좋아요 추가에서 좋아요가 이미 눌려져 있는 상태 조건문 삭제
=> [BE] fix: 좋아요 추가는 좋아요가 안눌려져 있는 상태에서만

server/src/main/java/com/example/group4eaten/like/service/LikeService.java, server/src/main/java/com/example/group4eaten/user/api/UserController.java
fix: 닉네임 수정 request body userForm 으로 받도록 수정
- 닉네임 수정 request body userForm 으로 받도록 수정
=> [BE] fix: 닉네임 수정 request body userForm 으로 받도록 수정

server/src/main/java/com/example/group4eaten/entity/Post.java, server/src/main/java/com/example/group4eaten/like/api/LikeApiController.java, server/src/main/java/com/example/group4eaten/post/api/PostApiController.java, server/src/main/java/com/example/group4eaten/post/repository/PostRepository.java, server/src/main/java/com/example/group4eaten/user/api/UserController.java
fix: CrossOrigin 어노테이션 추가, post repository outer join 쿼리 추가.
- CrossOrigin 어노테이션 추가, post repository outer join 쿼리 추가.
=> [BE] fix: CrossOrigin 어노테이션 추가, post repository outer join 쿼리 추가

server/src/main/java/com/example/group4eaten/post/repository/PostRepository.java
[BE] fix: userId 를 user_id로 바꿔서mypage api test 오류 해결
- fix: userId 를 user_id로 바꿔서mypage api test 오류 해결
=> [BE] fix: userId 를 user_id로 바꿔서mypage api test 오류 해결

server/src/main/java/com/example/group4eaten/post/service/PostService.java, server/src/main/java/com/example/group4eaten/user/service/UserService.java
fix: 회원 탈퇴 외래키 오류 해결
- 회원 탈퇴 외래키 오류 해결
=> [BE] fix: 회원 탈퇴 외래키 오류 해결

server/src/main/java/com/example/group4eaten/like/api/LikeApiController.java, server/src/main/java/com/example/group4eaten/post/api/PostApiController.java, server/src/main/java/com/example/group4eaten/user/api/UserController.java
fix: CrossOrigin에 frontend 서버 주소 추가
CrossOrigin에 frontend 서버 주소 추가
=> [BE]fix: CrossOrigin에 frontend 서버 주소 추가

client/src/api/post/detail.ts, client/src/api/post/newPost.ts, client/src/components/detail/Detail.tsx, client/src/components/new/NewPostList.tsx, client/src/components/popular/PopularPosts.tsx
=> fix: api 코드 수정

client/src/api/login/login.ts, client/src/api/myPage/changeNickname.ts, client/src/api/myPage/myPost.ts, client/src/api/post/addPost.ts, client/src/api/post/detail.ts, client/src/api/post/newPost.ts, client/src/api/post/popular.ts, client/src/api/signUp/IdExists.ts, client/src/api/signUp/SignUp.ts
fix: https 버그 수정
- http -> https
=> [FE] fix: https 버그 수정

server/src/main/java/com/example/group4eaten/post/service/PostService.java
전체 게시물 & 상세 게시물 조회 시 탈퇴회원의 글일 경우 닉네임이 "탈퇴함"으로 나오게
전체 게시물 & 상세 게시물 조회 시 탈퇴회원의 글일 경우 닉네임이 "탈퇴함"으로 나오게 수정
=> [BE]fix: 전체 게시물 & 상세 게시물 조회 시 탈퇴회원의 글일 경우 닉네임이 "탈퇴함"으로 나오게

server/src/main/java/com/example/group4eaten/post/service/PostService.java, server/src/main/resources/application.properties
fix: 탈퇴회원 인기게시물 확인
feat: https 접속 가능하게 변경
- fix: 탈퇴회원 인기게시물 확인
- feat: https 접속 가능하게 변경
=> [BE] fix: 탈퇴회원 인기게시물 확인

client/src/api/login/login.ts, client/src/api/myPage/changeNickname.ts, client/src/api/myPage/delete.ts, client/src/api/myPage/myPost.ts, client/src/api/post/addPost.ts, client/src/api/post/detail.ts, client/src/api/post/newPost.ts, client/src/api/post/popular.ts, client/src/api/signUp/IdExists.ts, client/src/api/signUp/SignUp.ts, client/src/components/addPost/Add.tsx, client/src/components/myPage/MyPage.tsx, client/src/components/new/NewPostList.tsx
fix: typeError 오류 수정
- typeError 오류 수정
=> [FE] fix: typeError 오류 수정

client/src/api/post/detail.ts, client/src/api/post/popular.ts, client/src/api/signUp/IdExists.ts, client/src/api/signUp/SignUp.ts, client/src/components/popular/PopularPosts.tsx, client/src/components/signUp/SignUp.tsx
=> [FE] fix: req, res 수정

client/src/api/signUp/IdExists.ts, client/src/components/myPage/MyPage.tsx
=> [FE] fix: err 수정

client/src/api/login/login.ts, client/src/api/myPage/changeNickname.ts, client/src/api/myPage/delete.ts, client/src/api/myPage/myPost.ts, client/src/api/post/addPost.ts, client/src/api/post/newPost.ts, client/src/api/post/popular.ts, client/src/api/signUp/IdExists.ts, client/src/api/signUp/SignUp.ts
=> [FE] fix: http로 수정

client/src/api/login/login.ts, client/src/api/myPage/changeNickname.ts, client/src/api/myPage/delete.ts, client/src/api/myPage/myPost.ts, client/src/api/post/addPost.ts, client/src/api/post/detail.ts, client/src/api/post/newPost.ts, client/src/api/post/popular.ts, client/src/api/signUp/IdExists.ts, client/src/api/signUp/SignUp.ts
=> [FE] fix: https로 다시 수정

client/package.json
=> [FE] fix: proxy 수정

client/src/api/login/login.ts, client/src/api/myPage/changeNickname.ts, client/src/api/myPage/delete.ts, client/src/api/myPage/myPost.ts, client/src/api/post/addPost.ts, client/src/api/post/detail.ts, client/src/api/post/newPost.ts, client/src/api/post/popular.ts, client/src/api/signUp/IdExists.ts, client/src/api/signUp/SignUp.ts
=> [FE] http로 수정

client/src/api/api.const.ts, client/src/api/hello.ts, client/src/api/post/newPost.ts, client/src/components/main/Main.tsx, client/src/components/new/NewPostList.tsx
server 오류 수정
- https로 변경
- API 에 https 포함
- api/hello test 포함
=> [FE] fix: server 오류 수정

server/src/main/java/com/example/group4eaten/WebConfig.java, server/src/main/java/com/example/group4eaten/like/api/LikeApiController.java, server/src/main/java/com/example/group4eaten/post/api/PostApiController.java, server/src/main/java/com/example/group4eaten/user/api/UserController.java
fix: webconfig 추가하고 crossorigin 삭제
crossorigin 어노테이션으로 cors 에러가 고쳐지지 않아서 webconfig 클래스를 추가하는 방식 시도
=> [BE]fix: webconfig 추가하고 crossorigin 삭제

server/src/main/java/com/example/group4eaten/post/dto/PostDto.java
fix: 빌드 에러 해결을 위해 @Builder.Default 추가
Lombok의 @Builder 주석으로 인하여 에러가 발생한 것으로 보임
edit_YN = false를 기본값으로 사용하기 위한 어노테이션 추가
=> [BE]fix: 빌드 에러 해결을 위해 @Builder.Default 추가

server/src/main/java/com/example/group4eaten/WebConfig.java
fix: webcofig corsfilter 설정
- fix: webcofig corsfilter 설정
=> [BE] fix: webcofig corsfilter 설정

server/src/main/java/com/example/group4eaten/WebConfig.java
fix: webcofig 수정
- fix: webcofig 수정
=> [BE] fix: webcofig 수정

server/src/main/java/com/example/group4eaten/CorsConfig.java, server/src/main/java/com/example/group4eaten/WebConfig.java
feat: corsconfig 추가/ fix:  webconfig 주석 처리
- feat: corsconfig 추가/ fix:  webconfig 주석 처리
=> [BE] feat: corsconfig 추가/ fix:  webconfig 주석 처리

server/src/main/java/com/example/group4eaten/user/api/UserController.java, server/src/main/resources/application.properties
fix: hello api 수정/ fix: keystore 관련 코드 삭제
- fix: hello api 수정/ fix: keystore 관련 코드 삭제
=> [BE] fix: hello api 수정/ fix: keystore 관련 코드 삭제

server/src/main/java/com/example/group4eaten/user/api/UserController.java
=> [BE]chore: 중괄호 추가

server/src/main/java/com/example/group4eaten/post/api/PostApiController.java
feat: mypage request header로 sessionId를 받아오지 않도록 변경
/mypage의 request header로 sessionId를 받아오던 것을 삭제함
=> [BE]feat: mypage request header로 sessionId를 받아오지 않도록 변경

README.md
=> Yhee527 patch 2

server/src/main/java/com/example/group4eaten/CorsConfig.java
corsorigin에 localhost:3000 추가
프론트엔드에서 작업할 수 있도록 localhost:3000을 CORS 허용 목록에 추가함
=> [BE]feat: corsorigin에 localhost:3000 추가
